export * from './ping.controller';
export * from './transportitas.controller';
export * from './recorridos.controller';
export * from './posiciones.controller';
export * from './rutas.controller';
export * from './vehiculos.controller';
export * from './tipovehiculo.controller';
export * from './licencias.controller';
export * from './transportistas.controller';
